server:
  port: 8080
  servlet:
    context-path: /ecommerce-api

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ecommerce_platform?useSSL=false&characterEncoding=utf8
    username: root
    password: 147308
    hikari:
      maximum-pool-size: 20
      connection-timeout: 3000

  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 2000

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

# 自定义配置
ecommerce:
  order:
    prefix: EC
    expire-minutes: 30