server:
  port: 8080
  servlet:
    context-path: /ecommerce-api

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ecommerce_platform?useSSL=false&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: 147308
    hikari:
      maximum-pool-size: 20
      connection-timeout: 3000

  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 2000

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

# 日志配置
logging:
  level:
    root: INFO
    com.ecommerce: DEBUG
    com.ecommerce.common.aop: DEBUG
    org.springframework.web: DEBUG
    org.mybatis: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"
  file:
    name: logs/ecommerce.log
    max-size: 10MB
    max-history: 30

# 自定义配置
ecommerce:
  order:
    prefix: EC
    expire-minutes: 30